### ISSUE TITLE
Busybox ash and init + MiniBox = Linux-Plus-Ultra???

### ISSUE THREAD

**Issue by Qwer-TeX** [plastic-bottleneck/Plus-Linux#1]
I found your project under page 17 of a google search. I see that it uses BusyBox instead of GNU, making it small and less bloated. 

And I also read about your putils project to find it it doesn't have much in it. My project [MiniBox](https://github.com/Qwer-TeX/minibox) has a little bit more utilities than putils so I though that maybe you can borrow from me, or vice versa? Or maybe have 2 versions of Plus-Linux, maybe 1 called Plus-Linux-Ultra with MiniBox, and you can add your own extra programs in the floppy?. 
I have a small shell but it isn't fully compatible with busybox ash or dash. I guess for now you could use busybox ash and Init + MiniBox.

If you see any source code bloat in my project, complain!!

**Comment by plastic-bottleneck** [comment]
Dear Robert,


it's great to hear that the Plus Linux community is more active than I initially thought. 
Thank you for suggesting MiniBox as a replacement for BusyBox in Plus Linux.

At the moment, I don't plan to continue the development of Plus Linux for a while, as I'm currently working on a complete kernel alternative written in C and Assembly for a separate Project.
This new project will also be a Unix-like(ish) alternative to the Linux kernel.

I have noted your request and will aim to implement it in the next update of Plus Linux.


Sincerely,
Paul
(Plastic Bottleneck)
